name: Generic Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 50
    - run: git fetch --tags

    - name: Setup .NET
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: "[ -f .ci-skip-tests ] && echo 'Skipping tests' || dotnet test --no-build --verbosity normal"

    - name: Pack
      if: github.ref == 'refs/heads/master'
      run: dotnet pack -c Debug -o Build

    - name: "Github packages: Nuget push"
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push --no-symbols --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" Build/*.nupkg
      
    - name: "Github packages: Cleanup"
      if: github.ref == 'refs/heads/master'
      uses: stripethree/gpr-janitor@dist
      with:
        dry-run: false
        keep-versions: 25
        min-age-days: 14
        versions-to-fetch: 20
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      